# tests of ical_network.py

# most of these are based on a specific fake ical file generated by make_testdata.py

# this 'test calendar' is small and its various properties are easy to check by counting-
# but for these tests to pass, we need to update test_answers = {} appropriately if we
# make any changes to  make_testdata.py :)

import unittest
import logging
import os
import pathlib
from ical_network import Meeting, load_single_ical, filter_meetings, find_people, make_graph
from make_testdata import make_testcal

#from make_testdata import make_testcal

test_answers = {'raw_length':9,
                'inhouse_length':5,
                'outofhouse_length':4,
                'one_to_one_length':6,
                'in_2025_length':7,
                'length_after_blacklist':8,
                'raw_people':6,  # there are 7 people in input people list, but one is a droid
                'people_after_blocklist':5, # 'unwanted@friend.net' is an example blocked address
                'interactions_p1_p2':8, # interactions between daniel@test.mail, sandra@test.mail
                'interactions_p1_p3':3} # inter between daniel@test.mail, felix@evil.mail}

testcolors = {'test.mail': {'r': 39, 'g': 105, 'b': 255, 'a': 0.5},
                'evil.mail': {'r': 163, 'g': 119, 'b': 212, 'a':  0.5},
                'pets.com': {'r': 37, 'g': 150, 'b': 190, 'a':  0.5},
                'friend.net': {'r': 37, 'g': 0, 'b': 200, 'a':  0.5}}
              
        
class TestDataExists(unittest.TestCase):
    # test that the fake data script is actually spitting anything out
    def test(self):
        try:
            os.remove('test_files/test.ical')
        except:
            pass
        make_testcal(testfile = 'test_files/test.ical')
        path = pathlib.Path("test_files/test.ical")
        self.assertEqual((str(path), path.is_file()), (str(path), True))
        
        
class TestDataLoads(unittest.TestCase):
    # test that we are loading a list of Meeting() with correct pre-filtering length 
    
    def setUp(self):
        self.meetings = load_single_ical("test_files/test.ical")
    
    def test_type(self):
        self.assertTrue(type(self.meetings) is list)
        self.assertTrue(type(self.meetings[0]) is Meeting)
        
    def test_raw_numbers(self):
        self.assertTrue(len(self.meetings) == test_answers['raw_length'])
        
        
class TestMeetingFiltering(unittest.TestCase):
    # test that various filtering options work
    
    def setUp(self):
        self.meetings = load_single_ical("test_files/test.ical")
        
    def test_filter_date(self):
        new_meetings = filter_meetings(self.meetings, dates = ['2025-01-01', '2025-12-31'])
        self.assertTrue(len(new_meetings) == test_answers['in_2025_length'])
    
    def test_filter_inhouse(self):
        new_meetings = filter_meetings(self.meetings, filter_group = 'single')
        self.assertTrue(len(new_meetings) == test_answers['inhouse_length'])
        
    def test_filter_outofhouse(self):
        new_meetings = filter_meetings(self.meetings, filter_group = 'multi')
        self.assertTrue(len(new_meetings) == test_answers['outofhouse_length'])
        
    def test_filter_one_to_one(self):
        new_meetings = filter_meetings(self.meetings, filter_one_to_one = True)
        self.assertTrue(len(new_meetings) == test_answers['one_to_one_length'])
        
        
class TestPeopleFiltering(unittest.TestCase):
    # test that we can block specific email addresses

    def setUp(self):
        self.meetings = load_single_ical("test_files/test.ical")
        
    def test_people_list(self):
        people = find_people(self.meetings, testcolors, blocklist = ['droid'])
        self.assertTrue(len(people) == test_answers['raw_people'])
        
    def test_blocklist(self):
        people = find_people(self.meetings, testcolors, 
                                blocklist = ['droid', 'unwanted@friend.net'])
        self.assertTrue(len(people) == test_answers['people_after_blocklist'])
        

class TestNodes(unittest.TestCase):
    # test that the graph nodes look as we expect them

    def setUp(self):
        self.meetings = load_single_ical("test_files/test.ical")
        self.people = find_people(self.meetings, testcolors, blocklist = ['droid'])
        self.graph = make_graph(self.people, self.meetings)
    
    def test_count_nodes(self):
        self.assertTrue(self.graph.number_of_nodes() == test_answers['raw_people'])
        
        
class TestEdges(unittest.TestCase):
    # test that the graph edges look as we expect them
    
    def setUp(self):
        self.meetings = load_single_ical("test_files/test.ical")
        self.people = find_people(self.meetings, testcolors, blocklist = ['droid'])
        self.graph = make_graph(self.people, self.meetings)
        
    def test_count_edges(self):
        wt = self.graph['daniel@test.mail']['sandra@test.mail']['weight']
        self.assertTrue(wt == test_answers['interactions_p1_p2'])
        wt = self.graph['daniel@test.mail']['felix@evil.mail']['weight']
        self.assertTrue(wt == test_answers['interactions_p1_p3'])
    
        
if __name__ == "__main_":
    unittest.main()